#Special configuration file to run tests on Travis-CI via GitHub notifications
#See http://travis-ci.org/ for details
#
#Note when testing Python 3, the 'python' command will invoke Python 3
#and similarly for PyPy too.
language: python

python:
#  - 2.7
#  - pypy
  - 3.4

install:
  - pip install coverage
  - pip install coveralls
  - /usr/bin/yes | python setup.py install

before_script:
  - pip freeze

script:
  - coverage run setup.py test
  - coverage report -m

after_success:
  - coveralls
